version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    container_name: gateway-service
    build:
      context: ./packages/api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4000:4000"
    env_file: ./packages/api-gateway/configs/.env

  auth-service:
    container_name: auth-service
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4001:4001"
    env_file: ./packages/auth-service/configs/.env

  company-service:
    container_name: company-service
    build:
      context: ./packages/company-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4004:4004"
    env_file: ./packages/company-service/configs/.env

  notification:
    container_name: notification-container
    build:
      context: ./packages/notification
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "4002:4002"
    env_file: ./packages/notification/configs/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ../notification/src:/app/src
